name: Release SemVer
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release new semantic version
    runs-on: ubuntu-latest
    outputs:
      didRelease: ${{ steps.semver.outputs.new_release_published }}
      newVersion: ${{ steps.semver.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        id: semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Normalize tag name
        if: steps.semver.outputs.new_release_published == 'true'
        id: normalize_tag
        run: |
          tag=${{ steps.semver.outputs.new_release_version }}
          echo "tag_name_no_v=${tag#v}" >> "$GITHUB_OUTPUT"